FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY packages/webapp/package*.json ./packages/webapp/
COPY packages/frontend/package*.json ./packages/frontend/
COPY scripts/ ./scripts/
RUN npm install

EXPOSE 5000 5001

CMD ["npm", "run", "dev:webapp"]
